### ISSUE TITLE
Sök fungerar inte

### ISSUE THREAD

**Issue by staffanm** [staffanm/lagen.nu#30]
Vad man än söker efter får man följande traceback:
```
500 Internal Server Error

Traceback (most recent call last):

  File "/home/staffan/wds/ferenda/ferenda/fulltextindex.py", line 911, in _decode_schema
    schema[fieldname] = self.from_native_field(fieldobject)

  File "/home/staffan/wds/ferenda/ferenda/fulltextindex.py", line 221, in from_native_field
    raise errors.SchemaMappingError("Native field %s cannot be mapped" % fieldobject)

ferenda.errors.SchemaMappingError: Native field {'type': 'string'} cannot be mapped

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/home/staffan/wds/ferenda/ferenda/wsgiapp.py", line 79, in __call__
    return self.search(environ, start_response)

  File "/home/staffan/wds/ferenda/lagen/nu/wsgiapp.py", line 31, in search
    res, pager = self._search_run_query(queryparams)

  File "/home/staffan/wds/ferenda/ferenda/wsgiapp.py", line 574, in _search_run_query
    res, pager = idx.query(query, pagenum=pagenum, **qpcopy)

  File "/home/staffan/wds/ferenda/ferenda/fulltextindex.py", line 635, in query
    relurl, payload = self._query_payload(q, pagenum, pagelen, **kwargs)

  File "/home/staffan/wds/ferenda/ferenda/fulltextindex.py", line 761, in _query_payload
    schema = self.schema()

  File "/home/staffan/wds/ferenda/ferenda/fulltextindex.py", line 614, in schema
    return self._decode_schema(res)

  File "/home/staffan/wds/ferenda/ferenda/fulltextindex.py", line 913, in _decode_schema
    raise errors.SchemaMappingError("%s: %s" % (fieldname, str(e)))

ferenda.errors.SchemaMappingError: dcterms_title: Native field {'type': 'string'} cannot be mapped

```
Felet har något att göra med en mismatch i Elasticsearchs schema ("mapping" på ES-språk). Problemet har uppstått tidigare, och jag tror det har gått att lösa med att ta bort databasen och omindexera (för att tvinga fram skapandet av en ny mapping).

Frågan är dock om vi verkligen behöver det exakta schemat för att kunna ställa en fråga. I anroparen _query_payload används det bara för att se om ett fält är en resource och då för att lägga till en ".iri" på frågeparametern. ElasticSearch.from_native_field skulle kunna göras mer robust istf att slänga ett SchemaMappingError när den inte kan mappa ett fält.

**Comment by staffanm** [comment]
Fixat i staffanm/ferenda@bc680b19 genom mer robust fulltext.ElasticSearch-impl som faller tillbaka på schemainformation från registrerade repos om inte mappingen kan parsas.
